package com.blitzbook.app;
import android.app.Activity;import android.content.Intent;import android.graphics.Bitmap;import android.graphics.Color;import android.net.Uri;import android.os.Bundle;import android.view.View;import android.view.Window;import android.webkit.*;import android.widget.ProgressBar;import java.io.*;
public class MainActivity extends Activity{
private static final String HOME_URL="https://nfl-all-time.vercel.app/";private static final String HOST="nfl-all-time.vercel.app";private WebView webView;private ProgressBar progressBar;private String phoneCss="";
@Override protected void onCreate(Bundle b){super.onCreate(b);Window w=getWindow();w.setStatusBarColor(Color.rgb(5,7,17));w.setNavigationBarColor(Color.rgb(5,7,17));setContentView(R.layout.activity_main);webView=findViewById(R.id.webView);progressBar=findViewById(R.id.progressBar);phoneCss=readAsset("apk-phone.css");WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setLoadsImagesAutomatically(true);s.setUseWideViewPort(false);s.setLoadWithOverviewMode(false);s.setSupportZoom(false);s.setCacheMode(WebSettings.LOAD_DEFAULT);s.setUserAgentString(s.getUserAgentString()+" BlitzbookAndroid/7.0 Mobile");webView.setWebChromeClient(new WebChromeClient(){public void onProgressChanged(WebView v,int p){progressBar.setProgress(p);progressBar.setVisibility(p>=100?View.GONE:View.VISIBLE);}});webView.setWebViewClient(new WebViewClient(){public void onPageStarted(WebView v,String u,Bitmap f){progressBar.setVisibility(View.VISIBLE);}public void onPageFinished(WebView v,String u){inject(v);}public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();String h=u.getHost();if(h!=null&&(h.equals(HOST)||h.endsWith(".vercel.app")))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}catch(Exception e){return false;}}});if(b==null)webView.loadUrl(HOME_URL);else webView.restoreState(b);}
private String readAsset(String n){StringBuilder o=new StringBuilder();try(BufferedReader br=new BufferedReader(new InputStreamReader(getAssets().open(n)))){String l;while((l=br.readLine())!=null)o.append(l).append('\n');}catch(Exception e){}return o.toString();}
private void inject(WebView v){String c=phoneCss.replace("\\","\\\\").replace("`","\\`").replace("${","\\${");String js="(function(){var vp=document.querySelector('meta[name=viewport]');if(!vp){vp=document.createElement('meta');vp.name='viewport';document.head.appendChild(vp);}vp.content='width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover';document.documentElement.classList.add('apk-mobile');var old=document.getElementById('apk-phone-style');if(old)old.remove();var st=document.createElement('style');st.id='apk-phone-style';st.textContent=`"+c+"`;document.head.appendChild(st);})();";v.evaluateJavascript(js,null);}
@Override public void onBackPressed(){String js="(function(){if(document.body.classList.contains('team-route-active')&&typeof routeHome==='function'){routeHome();return true;}return false;})()";webView.evaluateJavascript(js,r->{if("true".equals(r))return;if(webView.canGoBack())webView.goBack();else MainActivity.super.onBackPressed();});}
@Override protected void onSaveInstanceState(Bundle o){webView.saveState(o);super.onSaveInstanceState(o);}}
